# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='userfavorite',
            new_name='user',
        ),
    ]
